"""A population nobody chose, because "0 wrong" is otherwise a property of the sets.

`test_retrieval_quality.py` reports 45 right, 0 wrong, 6 refused over questions written
for this repository, and `test_generated_questions.py` reports 118 / 3 / 0 over one
question per provision HEADING. A review pointed out what those figures cannot tell
you: it wrote 24 unanswerable questions in the corpus's own vocabulary and 16 were
answered, and 38 answerable ones and got 27 right, 1 wrong, 10 refused - a refusal rate
of 26% against the README's 15%. The sets differ; the code between them did not.

So this is a third population, generated by a rule over the corpus's own CLAUSES rather
than its headings, which is a larger and harder set than either: a provision's opening
clause asked as a question, which that provision answers by construction.

What it finds, and this is stated here rather than in the README because it is a
property of the generator: two of its questions name no provision uniquely. PPC s.55,
s.60 and s.64 all begin "In every case in which", and truncating a clause to nine words
cuts off the word that distinguishes them - so the first citation is one of three
equally good matches. Both are served among the three passages. That is the generator's
limit and not a retrieval defect, which is the distinction a number alone cannot draw,
and the reason this file pins the mistakes individually.
"""

from __future__ import annotations

import pytest

from paklaw.answer import LawAssistant
from paklaw.ingest import build_checked
from tests.test_retrieval_quality import _corpus_rows

#: How many words of a clause make the question. Nine is enough to be a quotation and
#: short enough that some of them are ambiguous, which is the interesting part.
CLAUSE_WORDS = 9

#: The measurement, pinned. A change to the ranking moves these, and the point of
#: pinning them is that moving them is a decision rather than a side effect.
EXPECTED = {"asked": 31, "right": 30, "wrong": 1, "refused": 0}

#: The two that do not name one provision. Each is a clause opening shared by several
#: provisions, cut before the word that separates them - so what is asserted is that
#: the right provision is among the passages served, not that it is first.
AMBIGUOUS = {
    "in every case in which sentence of imprisonment for": ("Section 55 PPC", "Section 60 PPC"),
}


@pytest.fixture(scope="module")
def corpus():
    return build_checked(_corpus_rows(), source="fixtures")


@pytest.fixture(scope="module")
def assistant(corpus):
    return LawAssistant(corpus=corpus)


def _questions(corpus) -> list[tuple[str, str]]:
    """One question per provision: the first nine words of its first real clause.

    A rule, so that the set is not a choice. `isalpha` drops the clause markers and
    the transliterated terms that carry a hyphen or a colon, which is part of why two
    of these are ambiguous - said out loud rather than tuned away.
    """
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for provision in corpus.provisions:
        if provision.key in seen:
            continue
        seen.add(provision.key)
        for sentence in provision.text.replace(";", ".").split("."):
            words = _words(sentence)
            if len(words) < 6:
                continue
            out.append((" ".join(words[:CLAUSE_WORDS]).lower(), provision.citation().pretty()))
            break
    return out


def _words(sentence: str) -> list[str]:
    """The words of a clause, with the clause markers off and the terms kept.

    A first version of this took `w for w in sentence.split() if w.isalpha()`, which
    drops every transliterated term in the book - `qatl:`, `Ikrah-i-tam`, `Ta'zir` -
    because they carry a colon or a hyphen. s.303's clause came out as "whoever
    commits under shall be punished with imprisonment for", a sentence with every
    distinguishing word removed, and it was answered from s.65. That is a question the
    GENERATOR destroyed, and counting it as a retrieval mistake would have been
    measuring the probe.

    Punctuation comes off the ends and a word has to start with a letter, so the terms
    survive and the markers do not. 30 right instead of 29, and the one remaining
    mistake is a clause three provisions share.
    """
    out = []
    for raw in sentence.split():
        word = raw.strip('(),:;."“”’')
        if word and word[0].isalpha():
            out.append(word)
    return out


def _measure(corpus, assistant) -> tuple[dict, list[tuple[str, str, str]]]:
    right = wrong = refused = 0
    mistakes = []
    questions = _questions(corpus)
    for question, expected in questions:
        answer = assistant.answer(question, as_of="2026-01-01")
        if answer.refused:
            refused += 1
        elif answer.passages[0].citation == expected:
            right += 1
        else:
            wrong += 1
            mistakes.append((question, expected, answer.passages[0].citation))
    return (
        {"asked": len(questions), "right": right, "wrong": wrong, "refused": refused},
        mistakes,
    )


def test_the_population_is_generated_and_not_chosen(corpus):
    """One question per provision, by a rule, over every provision that has a clause."""
    questions = _questions(corpus)
    assert len(questions) == EXPECTED["asked"], len(questions)
    assert len({q for q, _ in questions}) == len(questions), "a question is duplicated"
    distinct = len({p.key for p in corpus.provisions})
    assert len(questions) <= distinct, (len(questions), distinct)


def test_the_figures_are_the_ones_this_file_states(corpus, assistant):
    measured, _ = _measure(corpus, assistant)
    assert measured == EXPECTED, measured
    assert measured["right"] + measured["wrong"] + measured["refused"] == measured["asked"]


def test_every_mistake_is_a_clause_several_provisions_share(corpus, assistant):
    """The claim this file makes about its own wrong answers, checked rather than
    asserted in prose: each is a question whose words do not name one provision."""
    _, mistakes = _measure(corpus, assistant)
    assert len(mistakes) == EXPECTED["wrong"], mistakes
    for question, expected, got in mistakes:
        key = question[:52]
        assert key in AMBIGUOUS, (question, expected, got)
        assert expected in AMBIGUOUS[key], (expected, AMBIGUOUS[key])
        assert got in AMBIGUOUS[key], (got, AMBIGUOUS[key])


def test_the_right_provision_is_among_the_passages_even_when_it_is_not_first(corpus, assistant):
    """Which is the difference between a wrong answer and an ambiguous question.

    A tool that serves three candidates for a question with three equally good answers
    has done its job; one that serves one of them as THE answer has not.
    """
    _, mistakes = _measure(corpus, assistant)
    for question, expected, _got in mistakes:
        answer = assistant.answer(question, as_of="2026-01-01")
        served = [p.citation for p in answer.passages]
        assert expected in served, (question, expected, served)


def test_nothing_built_from_a_clause_is_refused(corpus, assistant):
    """Every question here is a quotation from a provision, so the corpus holds its
    subject by construction and a refusal is this system failing to find what it has."""
    measured, _ = _measure(corpus, assistant)
    assert measured["refused"] == 0, measured


def test_this_set_is_harder_than_the_heading_set(corpus, assistant):
    """Otherwise it adds a number and not a measurement.

    The heading population asks "what counts as <heading>?", where the heading is the
    index entry a reader would look under. A clause is the statute's own prose, with
    the words it actually uses, and the citation is not in it.
    """
    measured, _ = _measure(corpus, assistant)
    accuracy = measured["right"] / measured["asked"]
    assert accuracy < 1.0, (
        "every clause question is answered correctly, so this set is not harder than "
        "the heading set and the claim above is wrong"
    )
    assert accuracy > 0.8, accuracy
